---
- name: restart rclone-mount
  systemd:
    daemon_reload: true
    name: rclone-mount
    state: restarted
  tags: rclone
  become: true

- name: restart rclone-http
  systemd:
    daemon_reload: true
    name: rclone-http
    state: restarted
  tags: rclone
  become: true