---
- name: restart rclone-crypt
  systemd:
    daemon_reload: true
    name: rclone-crypt
    state: restarted
  tags: rclone
  become: true

- name: restart rclone-http
  systemd:
    daemon_reload: true
    name: rclone-http
    state: restarted
  tags: rclone
  become: true